#### 1. Create a dataframe called views with two columns: datetime and user by reading feed-views.log.

In [1]:
import pandas as pd
views = pd.read_csv('../data/feed-views.log',
                    sep='\t',
                    names=['datetime', 'user'],
                    index_col='datetime',
                    engine='python')
views.index = pd.to_datetime(views.index)

views['year']= views.index.year
views['month']= views.index.month
views['day']= views.index.day
views['hour']= views.index.hour
views['minute']= views.index.minute
views['second']= views.index.second

views.head()

                             user  year  month  day  hour  minute  second
datetime
2020-04-17 12:01:08.463179  artem  2020      4   17    12       1       8
2020-04-17 12:01:23.743946  artem  2020      4   17    12       1      23
2020-04-17 12:27:30.646665  artem  2020      4   17    12      27      30
2020-04-17 12:35:44.884757  artem  2020      4   17    12      35      44
2020-04-17 12:35:52.735016  artem  2020      4   17    12      35      52

#### 2. Create the new column daytime.

In [2]:
dayTimes = ['night','early morning','morning','afternoon', 'early evening','evening']
dayTimings= [0,4,7,11,17,20,24]
views['daytime']= pd.cut(
    views['hour'],
    bins=dayTimings,
    labels=dayTimes,
    right=False
)
views= views.set_index('user')
views[5:15]

            year  month  day  hour  minute  second    daytime
user
oksana      2020      4   17    12      36      21  afternoon
oksana      2020      4   17    12      36      22  afternoon
artem       2020      4   17    13      55      19  afternoon
artem       2020      4   17    15       0      33  afternoon
artem       2020      4   17    15      14       9  afternoon
vladislav   2020      4   17    22      46      26    evening
artem       2020      4   18     0      30      45      night
konstantin  2020      4   18    10      53      52    morning
maxim       2020      4   18    10      56      55    morning
konstantin  2020      4   18    10      57      37    morning

#### 3. Calculate the number of elements in your dataframe.

In [9]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

#### 4. Sort the values in your dataframe by hour, minute, and second in ascending order simultaneously, not one by one.

In [4]:
views.sort_values(['hour','minute','second'],inplace=True)
views.head()

           year  month  day  hour  minute  second daytime
user
valentina  2020      5   15     0       0      13   night
valentina  2020      5   15     0       1       5   night
pavel      2020      5   12     0       1      27   night
pavel      2020      5   12     0       1      38   night
pavel      2020      5   12     0       1      55   night

#### 5. Calculate the minimum and maximum for the hours and the mode for the daytime categories.

In [5]:
night= views[views['daytime']=='night']
max_night= night[['hour']].max()
print("Max for night:\n",max_night)


print("="*80)

morning= views[views['daytime']=='morning']
min_morning= morning[['hour']].min()
print("\nMin for morning:\n",min_morning,'\n')

print("="*80)

night_max_hour_visit= night[night['hour']==max_night['hour']]
print('\n',night_max_hour_visit[0:1:],'\n')

print("="*80)

morning_min_hour_visit= morning[morning['hour']==min_morning['hour']]
print('\n',morning_min_hour_visit[0:1],'\n')

print("="*80,'\n')

hour_mode=views["hour"].mode()
print('Hour mode:\n',hour_mode,'\n')

print("="*80,'\n')

daytime_mode= views["daytime"].mode()
print('Daytime mode:\n',daytime_mode)

Max for night:
 hour    3
dtype: int32
================================================================================

Min for morning:
 hour    8
dtype: int32

================================================================================

             year  month  day  hour  minute  second daytime
user
konstantin  2020      4   19     3      23      35   night

================================================================================

            year  month  day  hour  minute  second  daytime
user
alexander  2020      5   15     8      16       3  morning

================================================================================

Hour mode:
 0    22
Name: hour, dtype: int32

================================================================================

Daytime mode:
 0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

#### 6. Show the three earliest and latest hours of the day and their corresponding usernames using nsmallest() and nlargest().

In [6]:
earliest = views.nsmallest(3, 'hour')
earliest

           year  month  day  hour  minute  second daytime
user
valentina  2020      5   15     0       0      13   night
valentina  2020      5   15     0       1       5   night
pavel      2020      5   12     0       1      27   night

In [7]:
latest= views.nlargest(3, 'hour')
latest

           year  month  day  hour  minute  second  daytime
user
ekaterina  2020      5   14    23       2      11  evening
ekaterina  2020      5   14    23       2      14  evening
ekaterina  2020      5   14    23       2      15  evening

#### 7. Use the describe() method to get the basic statistics for the columns.

In [8]:
stat = views.describe()
q1 = stat.loc['25%','hour']
q3 = stat.loc['75%','hour']
iqr = q3 - q1
iqr

np.float64(9.0)