#### 1. Read the JSON file that you saved in ex02.

One of the columns is a float, so let's define its format in Pandas using pd.options.display.float_format: floats should be displayed with two decimals.
There are missing values from the Model; do not do anything with them.

In [1]:
from operator import index
from tkinter.font import names

import numpy as np
import pandas as pd
import requests 

df = pd.read_json("../data/auto.json")
pd.options.display.float_format = '{:,.2f}'.format
df.set_index('CarNumber')

              Refund     Fines    Make    Model
CarNumber
Y163O8161RUS       2  3,200.00    Ford    Focus
E432XX77RUS        1  6,500.00  Toyota    Camry
7184TT36RUS        1  2,100.00    Ford    Focus
X582HE161RUS       2  2,000.00    Ford    Focus
92918M178RUS       1  5,700.00    Ford    Focus
...              ...       ...     ...      ...
Y163O8161RUS       2  1,600.00    Ford    Focus
M0309X197RUS       1 22,300.00    Ford    Focus
O673E8197RUS       2    600.00    Ford    Focus
8610T8154RUS       1  2,000.00    Ford    Focus
H419XE197RUS       2  8,594.59  Toyota  Corolla

[725 rows x 4 columns]

#### 2. Enrich the dataframe using a sample from that dataframe.

Create a sample with 200 new observations using random_state = 21.
The sample should not contain new combinations of the car number, make, and model, so the entire dataset will be consistent in this regard.
There are no restrictions on the refund and fines columns. You can randomly select a value from these columns and apply it to any car number.
Concatenate the sample with the initial dataframe to create a new dataframe, concat_rows.

In [2]:
np.random.seed(21)

temp_df = df.reset_index()
new_sample = temp_df[['CarNumber','Make','Model']].sample(n=200, random_state=21, replace=True)
new_sample['Refund'] = np.random.choice(df['Refund'], size=200)
new_sample['Fines'] = np.random.choice(df['Fines'], size=200)


concat_rows = pd.concat([new_sample, df]).set_index('CarNumber')
concat_rows

                    Make    Model  Refund     Fines
CarNumber
Y351O8197RUS        Ford    Focus       1    500.00
H917TC36RUS         Ford    Focus       2  8,500.00
C589EY154RUS        Ford    Focus       1  7,500.00
K846YE77RUS   Volkswagen   Passat       2  2,100.00
X4108H125RUS        Ford    Focus       2  1,500.00
...                  ...      ...     ...       ...
Y163O8161RUS        Ford    Focus       2  1,600.00
M0309X197RUS        Ford    Focus       1 22,300.00
O673E8197RUS        Ford    Focus       2    600.00
8610T8154RUS        Ford    Focus       1  2,000.00
H419XE197RUS      Toyota  Corolla       2  8,594.59

[925 rows x 4 columns]

#### 3. Enrich the concat_rows dataframe with a new column containing generated data.

Create a series named "Year" with random integers from 1980 to 2019.
Use np.random.seed(21) before generating the years.
Concatenate the series with the data frame and name it fines.

In [3]:
years    = np.random.randint(1980, 2019, size= len(concat_rows))
fines = concat_rows.copy()
fines['Year'] = years
fines

                    Make    Model  Refund     Fines  Year
CarNumber
Y351O8197RUS        Ford    Focus       1    500.00  2013
H917TC36RUS         Ford    Focus       2  8,500.00  2000
C589EY154RUS        Ford    Focus       1  7,500.00  2000
K846YE77RUS   Volkswagen   Passat       2  2,100.00  1982
X4108H125RUS        Ford    Focus       2  1,500.00  1994
...                  ...      ...     ...       ...   ...
Y163O8161RUS        Ford    Focus       2  1,600.00  2002
M0309X197RUS        Ford    Focus       1 22,300.00  2017
O673E8197RUS        Ford    Focus       2    600.00  2011
8610T8154RUS        Ford    Focus       1  2,000.00  1982
H419XE197RUS      Toyota  Corolla       2  8,594.59  1985

[925 rows x 5 columns]

#### 4. Enrich the dataframe with data from another dataframe.

Create a new dataframe with car numbers and their owners.
Get the most popular surnames in the US (you can find the file surname.json in the folder datasets).
Create a new series with the surnames. They should not contain special characters, such as commas or brackets. The count should equal the number of unique car numbers in the sample (use random_state = 21).
Create the dataframe owners with two columns: CarNumber and SURNAME.
Append five more observations to the fines dataframe. Come up with your own ideas for CarNumber, etc.
Delete the last 20 observations from the owners dataframe and add three new observations that are not the same as those added to the fines dataframe.
Join the two dataframes.
The new dataframe should contain only the car numbers that exist in both dataframes.
The new dataframe should contain all the car numbers from both dataframes.
The new dataframe should contain only the car numbers from the fines dataframe.
The new dataframe should contain only the car numbers from the owners dataframe.

In [4]:
surnames = pd.read_json("../data/surname.json")
car_numbers = fines.index.drop_duplicates()
surnames_sample = surnames[0].sample(n=len(car_numbers), random_state=21, replace=True).reset_index(drop=True)
car_numbers_series = pd.Series(car_numbers)
owner = pd.DataFrame({
    'CarNumber':car_numbers_series,
    'SURNAME':surnames_sample
}).set_index('CarNumber')
owner

               SURNAME
CarNumber
Y351O8197RUS     REYES
H917TC36RUS     ROGERS
C589EY154RUS   MORALES
K846YE77RUS   ANDERSON
X4108H125RUS      LONG
...                ...
O136HO197RUS      REED
O22097197RUS    MILLER
M0309X197RUS    TURNER
O673E8197RUS    BROOKS
8610T8154RUS   MENDOZA

[531 rows x 1 columns]

In [5]:

new_data = [
    {'CarNumber': 'Y123XX77', 'Make': 'Tesla', 'Model': 'Model 3', 'Fines': 500.0, 'Refund': 0, 'Year': 2022},
    {'CarNumber': 'A777AA99', 'Make': 'Mercedes-Benz', 'Model': 'S-Class', 'Fines': 2500.0, 'Refund': 1, 'Year': 2021},
    {'CarNumber': 'M555MM50', 'Make': 'BMW', 'Model': 'M5', 'Fines': 1500.0, 'Refund': 0, 'Year': 2019},
    {'CarNumber': 'B001BB11', 'Make': 'Audi', 'Model': 'RS6', 'Fines': 3000.0, 'Refund': 0, 'Year': 2023},
    {'CarNumber': 'E999EE178', 'Make': 'Porsche', 'Model': '911', 'Fines': 5000.0, 'Refund': 1, 'Year': 2020}
]
new_fines_rows = pd.DataFrame(new_data).set_index('CarNumber')
fines = pd.concat([fines,new_fines_rows])
fines

                       Make    Model  Refund    Fines  Year
CarNumber
Y351O8197RUS           Ford    Focus       1   500.00  2013
H917TC36RUS            Ford    Focus       2 8,500.00  2000
C589EY154RUS           Ford    Focus       1 7,500.00  2000
K846YE77RUS      Volkswagen   Passat       2 2,100.00  1982
X4108H125RUS           Ford    Focus       2 1,500.00  1994
...                     ...      ...     ...      ...   ...
Y123XX77              Tesla  Model 3       0   500.00  2022
A777AA99      Mercedes-Benz  S-Class       1 2,500.00  2021
M555MM50                BMW       M5       0 1,500.00  2019
B001BB11               Audi      RS6       0 3,000.00  2023
E999EE178           Porsche      911       1 5,000.00  2020

[930 rows x 5 columns]

In [6]:
owner = owner.iloc[:-20]

new_data = [
    {'CarNumber':'W65748364RUS', 'SURNAME': 'TSATURYAN'},
    {'CarNumber':'F34867728RUS', 'SURNAME': 'HOVANNISYAN'},
    {'CarNumber':'T12345678RUS', 'SURNAME': 'MINASYAN'}]
new_owner_rows = pd.DataFrame(new_data).set_index('CarNumber')
owner = pd.concat([owner, new_owner_rows])
owner

                  SURNAME
CarNumber
Y351O8197RUS        REYES
H917TC36RUS        ROGERS
C589EY154RUS      MORALES
K846YE77RUS      ANDERSON
X4108H125RUS         LONG
...                   ...
9464EX178RUS          LEE
O50197197RUS       HARRIS
W65748364RUS    TSATURYAN
F34867728RUS  HOVANNISYAN
T12345678RUS     MINASYAN

[514 rows x 1 columns]

In [7]:
inner_df = pd.merge(fines, owner, on='CarNumber', how='inner')
outer_df = pd.merge(fines, owner, on='CarNumber', how='outer')
left_df = pd.merge(fines, owner, on='CarNumber', how='left')
right_df = pd.merge(fines, owner, on='CarNumber', how='right')
print(inner_df.head())
print(outer_df.head())
print(left_df.head())
print(right_df.head())

                    Make   Model  Refund    Fines  Year   SURNAME
CarNumber
Y351O8197RUS        Ford   Focus       1   500.00  2013     REYES
H917TC36RUS         Ford   Focus       2 8,500.00  2000    ROGERS
C589EY154RUS        Ford   Focus       1 7,500.00  2000   MORALES
K846YE77RUS   Volkswagen  Passat       2 2,100.00  1982  ANDERSON
X4108H125RUS        Ford   Focus       2 1,500.00  1994      LONG
              Make  Model  Refund    Fines     Year SURNAME
CarNumber
704687163RUS  Ford  Focus    2.00 1,400.00 2,016.00   LOPEZ
704787163RUS  Ford  Focus    2.00 2,800.00 2,011.00  FLORES
704987163RUS  Ford  Focus    2.00 8,594.59 2,011.00  RIVERA
705287163RUS  Ford  Focus    2.00 2,000.00 2,013.00   LEWIS
705387163RUS  Ford  Focus    2.00   700.00 1,981.00    HILL
                    Make   Model  Refund    Fines  Year   SURNAME
CarNumber
Y351O8197RUS        Ford   Focus       1   500.00  2013     REYES
H917TC36RUS         Ford   Focus       2 8,500.00  2000    ROGERS
C589EY154RUS        Ford   Focus       1 7,500.00  2000   MORALES
K846YE77RUS   Volkswagen  Passat       2 2,100.00  1982  ANDERSON
X4108H125RUS        Ford   Focus       2 1,500.00  1994      LONG
              Make  Model  Refund     Fines     Year SURNAME
CarNumber
Y351O8197RUS  Ford  Focus    1.00    500.00 2,013.00   REYES
Y351O8197RUS  Ford  Focus    1.00 15,300.00 2,010.00   REYES
Y351O8197RUS  Ford  Focus    1.00  6,300.00 2,001.00   REYES
Y351O8197RUS  Ford  Focus    1.00  1,500.00 2,000.00   REYES
H917TC36RUS   Ford  Focus    2.00  8,500.00 2,000.00  ROGERS

In [8]:
print(len(fines))

years_table = pd.pivot_table(
    fines, 
    values='Fines', 
    index=['Make','Model'], 
    columns=['Year'], 
    aggfunc='sum')
years_table

930

Year                        1980      1981      1982       1983      1984  \
Make          Model
Audi                         NaN       NaN       NaN        NaN       NaN
              RS6            NaN       NaN       NaN        NaN       NaN
BMW                          NaN       NaN       NaN        NaN       NaN
              M5             NaN       NaN       NaN        NaN       NaN
Ford          Focus   135,694.59 72,594.59 77,989.17 153,989.17 56,594.59
              Mondeo         NaN       NaN       NaN        NaN       NaN
Mercedes-Benz S-Class        NaN       NaN       NaN        NaN       NaN
Porsche       911            NaN       NaN       NaN        NaN       NaN
Skoda         Octavia   8,594.59  6,000.00 18,400.00   2,600.00  8,594.59
Tesla         Model 3        NaN       NaN       NaN        NaN       NaN
Toyota        Camry          NaN       NaN  7,500.00  29,400.00       NaN
              Corolla  18,000.00 26,000.00       NaN   7,600.00  9,600.00
Volkswagen                   NaN       NaN       NaN        NaN       NaN
              Golf           NaN       NaN  2,800.00        NaN  4,500.00
              Jetta          NaN       NaN  9,000.00        NaN       NaN
              Passat    8,594.59       NaN  4,400.00        NaN  9,500.00
              Touareg   5,800.00       NaN       NaN        NaN       NaN
Volvo                        NaN       NaN       NaN        NaN       NaN

Year                        1985       1986       1987       1988       1989  \
Make          Model
Audi                         NaN        NaN        NaN        NaN        NaN
              RS6            NaN        NaN        NaN        NaN        NaN
BMW                          NaN        NaN        NaN        NaN        NaN
              M5             NaN        NaN        NaN        NaN        NaN
Ford          Focus   121,894.59 153,189.17 125,889.17 126,794.59 231,194.59
              Mondeo         NaN        NaN        NaN        NaN        NaN
Mercedes-Benz S-Class        NaN        NaN        NaN        NaN        NaN
Porsche       911            NaN        NaN        NaN        NaN        NaN
Skoda         Octavia     600.00   6,900.00   5,500.00  10,200.00  14,794.59
Tesla         Model 3        NaN        NaN        NaN        NaN        NaN
Toyota        Camry     1,000.00  13,000.00        NaN     500.00        NaN
              Corolla  12,794.59        NaN   3,200.00        NaN        NaN
Volkswagen                   NaN        NaN        NaN        NaN        NaN
              Golf     24,000.00        NaN        NaN        NaN        NaN
              Jetta          NaN        NaN        NaN        NaN        NaN
              Passat    4,500.00        NaN   7,400.00        NaN   5,200.00
              Touareg        NaN   1,300.00        NaN        NaN   6,300.00
Volvo                        NaN        NaN        NaN        NaN        NaN

Year                   ...       2014       2015       2016       2017  \
Make          Model    ...
Audi                   ...        NaN        NaN        NaN        NaN
              RS6      ...        NaN        NaN        NaN        NaN
BMW                    ...        NaN        NaN        NaN   8,594.59
              M5       ...        NaN        NaN        NaN        NaN
Ford          Focus    ... 113,200.00 255,800.00 194,994.59 147,994.59
              Mondeo   ...  46,200.00        NaN        NaN        NaN
Mercedes-Benz S-Class  ...        NaN        NaN        NaN        NaN
Porsche       911      ...        NaN        NaN        NaN        NaN
Skoda         Octavia  ...     800.00  12,000.00  27,000.00   1,900.00
Tesla         Model 3  ...        NaN        NaN        NaN        NaN
Toyota        Camry    ...   2,000.00  12,994.59        NaN        NaN
              Corolla  ...        NaN  10,400.00   6,800.00        NaN
Volkswagen             ...        NaN        NaN        NaN        NaN
              Golf     ...   5,800.00  10,600.00  20,800.00        NaN
              Jetta    ...     500.00        NaN        NaN   4,000.00
              Passat   ...   1,600.00   1,000.00   3,800.00   9,900.00
              Touareg  ...        NaN        NaN        NaN     500.00
Volvo                  ...        NaN        NaN        NaN        NaN

Year                       2018     2019     2020     2021   2022     2023
Make          Model
Audi                        NaN      NaN      NaN      NaN    NaN      NaN
              RS6           NaN      NaN      NaN      NaN    NaN 3,000.00
BMW                         NaN      NaN      NaN      NaN    NaN      NaN
              M5            NaN 1,500.00      NaN      NaN    NaN      NaN
Ford          Focus   59,694.59      NaN      NaN      NaN    NaN      NaN
              Mondeo        NaN      NaN      NaN      NaN    NaN      NaN
Mercedes-Benz S-Class       NaN      NaN      NaN 2,500.00    NaN      NaN
Porsche       911           NaN      NaN 5,000.00      NaN    NaN      NaN
Skoda         Octavia    300.00      NaN      NaN      NaN    NaN      NaN
Tesla         Model 3       NaN      NaN      NaN      NaN 500.00      NaN
Toyota        Camry         NaN      NaN      NaN      NaN    NaN      NaN
              Corolla 15,900.00      NaN      NaN      NaN    NaN      NaN
Volkswagen                  NaN      NaN      NaN      NaN    NaN      NaN
              Golf          NaN      NaN      NaN      NaN    NaN      NaN
              Jetta         NaN      NaN      NaN      NaN    NaN      NaN
              Passat  15,000.00      NaN      NaN      NaN    NaN      NaN
              Touareg       NaN      NaN      NaN      NaN    NaN      NaN
Volvo                       NaN      NaN      NaN      NaN    NaN      NaN

[18 rows x 44 columns]

In [9]:
fines.to_csv('../data/fines.csv')
owner.to_csv('../data/owner.csv')