#### 1. Load the JSON file that you created in the previous exercise into a dataframe.

In [1]:
from operator import index

import pandas as pd
df = pd.read_json('../data/auto.json')
df = df.set_index('CarNumber')
df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

#### 2. Make the following selections: 
Display the rows where the fines are greater than 2,100.
Display the rows where the fines are greater than 2,100 and the refund equals 2.
Display the rows where the models are from the list: [’Focus’, ’Corolla’].
Display the rows where the car number is from the list: [’Y7689C197RUS’, ’92928M178RUS’, ’7788KT197RUS’, ’H115YO163RUS’, ’X758HY197RUS’].

In [2]:
fines_more_2000 = df[df['Fines']>2000]
fines_more_2000

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
7184TT36RUS        1   2100.000000        Ford    Focus
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[459 rows x 4 columns]

In [3]:
fines_more_2100_refund_2 = df[(df['Fines']>2100) & (df['Refund']==2)]
fines_more_2100_refund_2

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

In [4]:
focus_or_corolla = df[(df['Model']=='Corolla') | (df['Model']=='Focus')]
focus_or_corolla

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [5]:
number_arr = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
result = df[df.index.isin(number_arr)]
result

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

#### 3. Make the aggregations with the make and model.
Display the median fines grouped by make.
Display the median fines grouped by make and model.
Display the number of fines grouped by make and model to understand if we can trust the median values.
Display the minimum and maximum fines grouped by make and model to better understand the variance.
Display the standard deviation of fines grouped by make and model to better understand the variance.

In [6]:
median_fines_make = df.groupby('Make')['Fines'].median()
median_fines_make

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [7]:
median_fines_make_model = df.groupby(['Make','Model'])['Fines'].median()
median_fines_make_model

Make        Model
Audi                   4200.0
BMW                    6500.0
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen             7400.0
            Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Volvo                  8500.0
Name: Fines, dtype: float64

In [8]:
count_by_make_model = df.groupby(['Make', 'Model'])['Fines'].count()
count_by_make_model

Make        Model
Audi                     1
BMW                      3
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen               3
            Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Volvo                    2
Name: Fines, dtype: int64

In [9]:
min_max_make_model = df.groupby(['Make', 'Model'])['Fines'].agg(['min','max'])
min_max_make_model

                       min            max
Make       Model
Audi                4200.0    4200.000000
BMW                 3000.0    8594.586466
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen          1300.0    7900.000000
           Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    8594.586466
Volvo               6800.0   10200.000000

In [10]:
standard_deviation = df.groupby(['Make', 'Model'])['Fines'].std()
standard_deviation

Make        Model
Audi                            NaN
BMW                     2826.561226
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen              3674.688195
            Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Volvo                   2404.163056
Name: Fines, dtype: float64

#### 4. Make aggregations with car numbers.
Display the car numbers, grouped by the number of fines in descending order. We want to find those who most often violated the law.
Select from the initial dataframe all the rows corresponding to the top-1 car number. We want to zoom in a little bit.
Display the car numbers grouped by sum of fines in descending order. We want to find those who paid the most.
Select all the rows corresponding to the top-1 car number from the initial dataframe. We want to zoom in a little bit.
Display a table that answers the question, "Are there any car numbers connected to different models?"

In [11]:
group = df.groupby('CarNumber')
fines_top = group['Fines'].count().sort_values(ascending=False)
fines_top

CarNumber
Y7689C197RUS    4
92928M178RUS    4
7788KT197RUS    4
H115YO163RUS    3
X758HY197RUS    3
               ..
E42577152RUS    1
E42377152RUS    1
E41977152RUS    1
E41577152RUS    1
H917TC36RUS     1
Name: Fines, Length: 531, dtype: int64

In [12]:
top_car_num = fines_top.index[0]
result = df[df.index == top_car_num]
result

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

In [13]:
top_total_fines = df.groupby('CarNumber')['Fines'].sum().sort_values(ascending=False)
top_total_fines

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
83218C154RUS       100.0
Y195O8161RUS       100.0
K376HE161RUS       100.0
705787163RUS       100.0
K326T8197RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [14]:
high_num = df.index[0]
result = df[df.index == high_num]
result

              Refund   Fines  Make  Model
CarNumber
Y163O8161RUS       2  3200.0  Ford  Focus
Y163O8161RUS       2  1600.0  Ford  Focus

In [15]:
theory = df.groupby('CarNumber')['Model'].nunique().sort_values(ascending=False)
theory = theory[theory > 1]
theory

CarNumber
E316EH197RUS    2
Name: Model, dtype: int64